#!/usr/bin/env bash

set -e

# launch and background our oauth2_proxy, bound only to local traffic
bin/oauth2_proxy -upstream file:///dev/null -http-address=127.0.0.1:4180 -config="oauth2_proxy.cfg" &

# launch the upstream buildpack's nginx + PHP-fpm
vendor/bin/heroku-php-nginx -C oauth2_proxy.nginx.conf web/
